### ISSUE TITLE
[TASK]Get user Details endpoint

### ISSUE THREAD

**Issue by Rethakgetse-Manaka** [COS301-SE-2024/occupi#137]
**Task Request**
Implement the get user details for the frontend.

- [x] Get the user data
- [x] Implement error handling
- [x] Implement testing

@Rethakgetse-Manaka , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.

**Comment by waveyboym** [comment]
I implemented testing for this endpoint as well as refactored some of the logic
