### ISSUE TITLE
[TASK] Auth endpoint for 2fa

### ISSUE THREAD

**Issue by waveyboym** [COS301-SE-2024/occupi#140]
**Task Request**

- [x] Implement backend logic for 2fa
- [x] Integrate 2fa with sms but this will require you to make use of an sms library and to also verify if numbers and regions are correct

@u21631532, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.

**Comment by u21631532** [comment]
no sms required or used
