### ISSUE TITLE
[TASK] Unit & integration Testing for Frontend Web

### ISSUE THREAD

**Issue by Rethakgetse-Manaka** [COS301-SE-2024/occupi#18]
**Please implement frontend testing for the web implementation. Please use the testing framework, Jest unless you find better testing frameworks and can justify why we should use those testing frameworks.**

- [x] Research and learn how Jest works and how to write test code
- [x] Implement testing to frontend code.
- [ ] Look into integration testing when you are complete with this task.

@Tinashe-Austin , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Read through the jest documentation.
Look into integration testing for when we need to do integration testing you have an idea of how it works

**Comment by Tinashe-Austin** [comment]
there is a weird import causing errors but im basically done
