### ISSUE TITLE
[TASK] Management Terminal Rooms Feature

### ISSUE THREAD

**Issue by Tinashe-Austin** [COS301-SE-2024/occupi#280]
**Task Request**

- [x] Create Rooms
- [x] Update Rooms
- [x] delete Rooms
- [x] Disable Rooms

<@Tinashe-Austin>, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.

**Comment by waveyboym** [comment]
@Tinashe-Austin don't forget that you can also upload room images😋
https://docs.occupi.tech/api-documentation/api-usage#upload-room-image
