### ISSUE TITLE
[TASK] Complete Settings Page

### ISSUE THREAD

**Issue by Tinashe-Austin** [COS301-SE-2024/occupi#282]
**Task Request**

- [x] Create Notifications
- [x] Create About Page
- [x] Create Security Page

<@Tinashe-Austin>, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.

**Comment by waveyboym** [comment]
@Tinashe-Austin this issue is a duplicate of pre-existing issue here: #268
