### ISSUE TITLE
Email sending

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#4]
Successfully send an email to an email address using Go.

- [ ] Find out how we can format the email layout as well. Possibly search for a golang related library that can achieve such functionality. Do not interact with native api's such as raw SMTP.
- [ ] The email must send A randomly generated 6 digit code to a valid email address. The email may not arrive in your inbox thus be sure to check your spam

@Rethakgetse-Manaka , please tick off as you complete each task by clicking on the task you are done with in this comment

**Comment by Rethakgetse-Manaka** [comment]
This issue  is being closed because I have fully implemented and unit tested this functionality. All that is left to do a PR and merge the changes
