### ISSUE TITLE
[TASK] ReadME for frontend mobile

### ISSUE THREAD

**Issue by u21631532** [COS301-SE-2024/occupi#9]
**Task Request**

- [x] can someone please make the 2 iphones overlap each other
just like how it is in the figma

@waveyboym , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
File under discussion: https://github.com/COS301-SE-2024/occupi/blob/develop/frontend/occupi-mobile/README.md?plain=1#L5-L6

**Comment by waveyboym** [comment]
@u21631532 , completed
